default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: exercise_user
  password: exercise_user
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: exercise_dev

test:
  <<: *default
  database: exercise_test
